language: python
os:
  - linux
python:
  - "3.4"
  - "2.7"

before_install:
  sudo apt-get update -q
  sudo apt install libblas-dev liblapack-dev

install:
  - pip install .
  - pip install -r requirements.txt
script: py.test
