language: python
os:
  - linux
python:
  - "3.5"
  - "2.7"

before_install:
  - sudo apt-get -yy update
  - sudo apt-get install -y libblas-dev liblapack-dev

install:
  - pip install .
  - pip install -r requirements.txt
script: py.test
